name: Generate Snake

on:
  schedule:
    # Her 12 saatte bir çalışır (GitHub sunucularını çok yormamak için 12 idealdir)
    - cron: "0 */12 * * *"
  
  # Actions sekmesinden manuel olarak çalıştırmana olanak tanır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Botun dosyaları output dalına yazabilmesi için gereken yetki
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mhmtemnbgr1
          # Hem normal hem de karanlık mod için iki ayrı SVG üretir
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
